### ISSUE TITLE
Should Debugger.enable be sync or async?

### ISSUE THREAD

**Issue by brendyna** [WICG/devtools-protocol#8]
@pavelfeldman, @RByers: we notice in some of the CDP tests that `Debugger.enable` appears to be synchronous. 

Here's an example from this test: https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/inspector-protocol/debugger/postMessage-on-pause.js

```
dp.Debugger.enable();
dp.Runtime.evaluate({expression: `
    var messageDispatched = false;
    window.addEventListener('message', event => {
      messageDispatched = true;
      debugger;
    }, true);

    (function testFunction() {
      window.postMessage('test', '*');
      debugger;
    })()
  `});
```

To us, it seems like this should be asynchronous (e.g. any test should promise-chain `Debugger.enable` and only call, say in the example above, `dp.Runtime.evaluate` once the promise is resolved for `Debugger.enable`).

Is our understanding there correct? If so, is it possible these tests work on your end due to good luck with timing? Or did you intend for `Debugger.enable` to indeed by synchronous?

Our concern here is we'd potentially break clients which expect `Debugger.enable` to be synchronous if EDP's expectation is that it be async.

**Comment by pavelfeldman** [comment]
It is not synchronous, but we assume that it is going to be serialized with the subsequent calls. We should not assume that, we should put await before it...

**Comment by brendyna** [comment]
Got it, thank you!
